### ISSUE TITLE
Milestone #5 Report due to 04.11.18

### ISSUE THREAD

**Issue by buseece** [bounswe/bounswe2018group1#121]
Draft report can be found at: 

https://www.overleaf.com/9368836883qwwjdbrksmhb

Anyone wants to contribute to the report please state the name of the subject in the comments. 

Possible parts:

- [x] Executive Summary 
- [x] List and Status of Deliverables
- [x] Summary of coding 
- [x] Design
- [x] Project Plan
- [x] Code
- [x] Management
- [x] Conclusion and Assessment

**Comment by buseece** [comment]
I will work on Executive Summary and List and Status of Deliverables
