### ISSUE TITLE
Milestone #5 deliverables

### ISSUE THREAD

**Issue by buseece** [bounswe/bounswe2018group1#122]
- [x]  Register with validation

- [x] Login with validation

- [x] Show User profile page

- [x] Edit user profile page

- [x] Show memory

- [x] Add memory

- [x] Milestone report

- [x] Milestone presentation

**Comment by buseece** [comment]
Here are the issues that we need to address in our milestone. Please cross the subjects that are done and try to finish your work concerning these subjects.
