### ISSUE TITLE
Milestone report 

### ISSUE THREAD

**Issue by cemal-aytekin-2015400126** [bounswe/bounswe2018group1#87]
The following items should be written on report

* [ ] Executive Summary: Summary of project status and any changes that are planned for moving forward.

* [ ] List and status of deliverables

* [ ] Evaluation of the status of deliverables and its impact on plan

* [ ] A summary of coding work done by each team member (In tabular format)(bunu herkes yazacak)

* [ ] Software development infrastructure: Your API assignment (from development to deployment).

* [ ] Evaluation of tools and managing the project.
